DROP TABLE IF EXISTS USERS;
CREATE TABLE Users (
    ID SERIAL PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(25) NOT NULL
);

DROP TABLE IF EXISTS ADMINS;
CREATE TABLE Admins (
   user_id BIGINT PRIMARY KEY,
   FOREIGN KEY (user_id) REFERENCES Users(id)
);

